### ISSUE TITLE
[FEAT] iOS 3차 과제

### ISSUE THREAD

**Issue by dlwns33** [29th-WE-SOPT-iOS-Part/ChoiYiJoon#7]
## 📌  Feature Issue

3주차 과제는 이번에 배운 TableView와 CollectionView를 활용하여 Youtube 홈 화면을 구성해보는 것입니다!
## 📝  To-do

▶️ UI 구성하기
- [x] 채널정보 CollectionView 만들기
- [x] CollectionView custom cell 만들기 (Xib)
- [x] 동영상정보 TableView 만들기
- [x] TableView custom cell 만들기 (Xib)

▶️ 기능 구현하기
- [x] 홈 화면과 연결하기

▶️ 도전과제 구현하기
- [ ] 카테고리 셀 구현하기 (dynamic cell)
